"""empty message

Revision ID: 4f17f00a6176
Revises: a5cffa318ac2
Create Date: 2023-12-15 13:37:53.520314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f17f00a6176'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('director', sa.String(), nullable=True),
    sa.Column('opening_crawl', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('people',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('mass', sa.String(), nullable=True),
    sa.Column('hair_color', sa.String(), nullable=True),
    sa.Column('skin_color', sa.String(), nullable=True),
    sa.Column('birth_year', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('planets',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.String(), nullable=True),
    sa.Column('rotation_period', sa.String(), nullable=True),
    sa.Column('population', sa.String(), nullable=True),
    sa.Column('terrain', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('species',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('average_height', sa.String(), nullable=True),
    sa.Column('average_lifespan', sa.String(), nullable=True),
    sa.Column('hair_colors', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('starships',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('vehicle_class', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('cost_in_credits', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicles',
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('vehicle_class', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('cost_in_credits', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('characters_in_films',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.uid'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.uid'], ),
    sa.PrimaryKeyConstraint('film_id', 'person_id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('starship_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('specie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.uid'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.uid'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.uid'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['species.uid'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.uid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.uid'], ),
    sa.PrimaryKeyConstraint('user_id', 'film_id', 'planet_id', 'person_id', 'starship_id', 'vehicle_id', 'specie_id')
    )
    op.create_table('films_planets',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.uid'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.uid'], ),
    sa.PrimaryKeyConstraint('film_id', 'planet_id')
    )
    op.create_table('films_species',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.uid'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.uid'], ),
    sa.PrimaryKeyConstraint('film_id', 'species_id')
    )
    op.create_table('films_starships',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.uid'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.uid'], ),
    sa.PrimaryKeyConstraint('film_id', 'starship_id')
    )
    op.create_table('films_vehicles',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.uid'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.uid'], ),
    sa.PrimaryKeyConstraint('film_id', 'vehicle_id')
    )
    op.create_table('species_people',
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.uid'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.uid'], ),
    sa.PrimaryKeyConstraint('species_id', 'person_id')
    )
    op.create_table('starship_pilots',
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.uid'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.uid'], ),
    sa.PrimaryKeyConstraint('starship_id', 'person_id')
    )
    op.create_table('vehicle_pilots',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.uid'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.uid'], ),
    sa.PrimaryKeyConstraint('vehicle_id', 'person_id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('vehicle_pilots')
    op.drop_table('starship_pilots')
    op.drop_table('species_people')
    op.drop_table('films_vehicles')
    op.drop_table('films_starships')
    op.drop_table('films_species')
    op.drop_table('films_planets')
    op.drop_table('favorites')
    op.drop_table('characters_in_films')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('starships')
    op.drop_table('species')
    op.drop_table('planets')
    op.drop_table('people')
    op.drop_table('films')
    # ### end Alembic commands ###
