"""empty message

Revision ID: c2b34fe0b051
Revises: 4f17f00a6176
Create Date: 2023-12-15 17:44:01.063257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b34fe0b051'
down_revision = '4f17f00a6176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('film_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('person_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('starship_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('specie_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               existing_server_default=sa.text("nextval('vehicles_uid_seq'::regclass)"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('vehicles_uid_seq'::regclass)"))

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('specie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('starship_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('person_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('film_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
